defmodule VgApp.Repo.Migrations.Vs000bAccountsHardening do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:account_roles, [:user_id, :role],
                     name: "account_roles_unique_active_role_per_user_index"
                   )

    create unique_index(:account_roles, [:user_id, :role], name: "account_roles_user_role_idx")
  end

  def down do
    drop_if_exists unique_index(:account_roles, [:user_id, :role],
                     name: "account_roles_user_role_idx"
                   )

    create unique_index(:account_roles, [:user_id, :role],
             name: "account_roles_unique_active_role_per_user_index"
           )
  end
end
