defmodule VgApp.Repo.Migrations.Vs000bAccountsFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
      add :state, :text, null: false, default: "pending_confirmation"
    end

    create table(:user_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "user_profiles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :phone_number, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:user_profiles, [:user_id],
             name: "user_profiles_unique_user_profile_per_user_index"
           )

    create table(:consent_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "consent_records_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :consent_type, :text, null: false
      add :consent_version, :text, null: false
      add :state, :text, null: false, default: "accepted"
      add :accepted_at, :utc_datetime_usec, null: false
      add :revoked_at, :utc_datetime_usec
      add :source, :text, null: false
      add :ip_address_hash, :text
      add :user_agent_hash, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:consent_records, [:user_id, :consent_type, :consent_version],
             name: "consent_records_uact_per_user_idx"
           )

    create table(:account_roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "account_roles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :role, :text, null: false
      add :state, :text, null: false, default: "active"

      add :granted_by_user_id,
          references(:users,
            column: :id,
            name: "account_roles_granted_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :granted_at, :utc_datetime_usec, null: false
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:account_roles, [:user_id, :role],
             name: "account_roles_unique_active_role_per_user_index"
           )
  end

  def down do
    drop constraint(:account_roles, "account_roles_user_id_fkey")

    drop constraint(:account_roles, "account_roles_granted_by_user_id_fkey")

    drop_if_exists unique_index(:account_roles, [:user_id, :role],
                     name: "account_roles_unique_active_role_per_user_index"
                   )

    drop table(:account_roles)

    drop constraint(:consent_records, "consent_records_user_id_fkey")

    drop_if_exists unique_index(:consent_records, [:user_id, :consent_type, :consent_version],
                     name: "consent_records_uact_per_user_idx"
                   )

    drop table(:consent_records)

    drop constraint(:user_profiles, "user_profiles_user_id_fkey")

    drop_if_exists unique_index(:user_profiles, [:user_id],
                     name: "user_profiles_unique_user_profile_per_user_index"
                   )

    drop table(:user_profiles)

    alter table(:users) do
      remove :state
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end
  end
end
